apiVersion: v1
kind: Namespace
metadata:
  name: platform-gameservers-eu-west
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agones-sdk
  namespace: platform-gameservers-eu-west
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agones-sdk
  namespace: platform-gameservers-eu-west
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agones-sdk
subjects:
  - kind: ServiceAccount
    name: agones-sdk
    namespace: platform-gameservers-eu-west
---
apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: arena-deathmatch
  namespace: platform-gameservers-eu-west
spec:
  replicas: 2
  template:
    metadata:
      labels:
        platform.game/id: arena
        platform.game/mode: deathmatch
        platform.game/build: dev
        platform.game/build-id: sha256-00000000000000000000000000000000
        platform.game/region: eu-west
        platform.game/protocol: udp
    spec:
      ports:
        - name: game
          containerPort: 7000
          protocol: UDP
        - name: http
          containerPort: 7001
          protocol: TCP
      template:
        spec:
          containers:
            - name: game-server
              image: gameservice-simulator:dev
              imagePullPolicy: Never
              env:
                - name: SIMULATOR_ADDR
                  value: ":7001"
                - name: AGONES_DYNAMIC_ASSIGNMENT
                  value: "true"
                - name: SERVER_CLAIM_PUBLIC_KEY
                  valueFrom:
                    secretKeyRef:
                      name: gameservice-server-claims
                      key: public-key
                - name: AGONES_ENABLED
                  value: "true"
                - name: CONTROL_API_URL
                  value: __CONTROL_API_URL__
              securityContext:
                runAsNonRoot: true
                runAsUser: 65532
                readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
                capabilities: { drop: [ALL] }
              resources:
                requests: { cpu: 100m, memory: 128Mi }
                limits: { cpu: "1", memory: 512Mi }
              readinessProbe:
                httpGet: { path: /health/ready, port: 7001 }
                periodSeconds: 5
---
apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: arena-deathmatch
  namespace: platform-gameservers-eu-west
spec:
  fleetName: arena-deathmatch
  policy:
    type: Buffer
    buffer:
      bufferSize: 1
      minReplicas: 2
      maxReplicas: 2
