services:
  control-api:
    networks:
      - default
      - kind
  matchmaking-worker:
    networks:
      - default
      - kind

networks:
  default: {}
  kind:
    external: true
    name: kind
