{{- if .Values.externalSecrets.enabled }}
{{- range $namespace := list .Values.namespace.app .Values.namespace.gameservers }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $.Values.externalSecrets.targetSecretName }}
  namespace: {{ $namespace }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ $.Values.externalSecrets.secretStoreRef.name }}
    kind: {{ $.Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ $.Values.externalSecrets.targetSecretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ $.Values.externalSecrets.remoteKey | quote }}
---
{{- end }}
{{- end }}
