{{- if .Values.gameServer.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gameservice-gameserver-default-deny
  namespace: {{ .Values.namespace.gameservers }}
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gameservice-gameserver-ingress
  namespace: {{ .Values.namespace.gameservers }}
spec:
  podSelector: { matchLabels: { app.kubernetes.io/name: gameservice-server } }
  policyTypes: [Ingress]
  ingress:
    - ports:
        - { protocol: UDP, port: {{ .Values.gameServer.gamePort }} }
        - { protocol: TCP, port: {{ .Values.gameServer.httpPort }} }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gameservice-gameserver-egress
  namespace: {{ .Values.namespace.gameservers }}
spec:
  podSelector: { matchLabels: { app.kubernetes.io/name: gameservice-server } }
  policyTypes: [Egress]
  egress:
    - to: [{ namespaceSelector: { matchLabels: { kubernetes.io/metadata.name: {{ .Values.namespace.app }} } } }]
      ports: [{ protocol: TCP, port: {{ .Values.service.port }} }]
    - to: [{ namespaceSelector: { matchLabels: { kubernetes.io/metadata.name: kube-system } } }]
      ports:
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 53 }
{{- end }}
